relativeURLs = true
title = "Chrisma D'Souza"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[params]
    shortbio = "Senior Research Associate at IFMR LEAD | Applied Microeconomics, Political Economy, Environment & Development Economics"
    logo = "Capture.JPG"
