relativeURLs = true
title = "Chrisma D'Souza"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[params]
    shortbio = "PhD student in Applied Economics and Management, Cornell University"
    logo = "Capture.JPG"
